apiVersion: v2
appVersion: "20210328"
dependencies:
- name: common
  repository: https://truecharts.org
  version: 8.9.10
deprecated: false
description: Spotweb is a decentralized usenet community based on the Spotnet protocol.
home: https://github.com/truecharts/apps/master/charts/incubator/spotweb
icon: https://raw.githubusercontent.com/spotweb/spotweb/9af0ade0f618675206dcf1f744dbb3c1eae70e5a/images/spotnet.gif
keywords:
- usenet
- spotweb
- spotnet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: spotweb
sources:
- https://github.com/spotweb/spotweb
- https://hub.docker.com/r/jgeusebroek/spotweb
version: 0.0.1
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
