image:
  repository: jgeusebroek/spotweb
  pullPolicy: IfNotPresent
  tag: php8.1@sha256:9970d2a23b1bfb3ca7736ed9c544320df843546fc7c76f6e7c0a7034adfe1148

# See more environment variables in the babybuddy documentation
# https://hub.docker.com/r/jgeusebroek/spotweb
env:
  # TZ:
  SPOTWEB_CRON_RETRIEVE: "*/15 * * * *"

envTpl:
  SPOTWEB_DB_TYPE: "pdo_pgsql"
  SPOTWEB_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase }}"
  SPOTWEB_DB_USER: "{{ .Values.postgresql.postgresqlUsername }}"
  SPOTWEB_DB_PORT: "5432"

envValueFrom:
  SPOTWEB_DB_PASS:
    secretKeyRef:
      name: dbcreds
      key: postgresql-password
  SPOTWEB_DB_HOST:
    secretKeyRef:
      name: dbcreds
      key: plainhost

initContainers:
  1-init-db:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ["php /var/www/spotweb/bin/upgrade-db.php -reset-password admin -set-systemtype single"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: false
      runAsNonRoot: false
    env:
      - name: SPOTWEB_DB_TYPE
        value: "pdo_pgsql"
      - name: SPOTWEB_DB_NAME
        value: {{ .Values.postgresql.postgresqlDatabase | quote }}
      - name: SPOTWEB_DB_USER
        value: {{ .Values.postgresql.postgresqlUsername | quote }}
      - name: SPOTWEB_DB_PORT
        value: "5432"
      - name: SPOTWEB_DB_PASS
        valueFrom:
          secretKeyRef:
            name: dbcreds
            key: postgresql-password
      - name: SPOTWEB_DB_HOST
        valueFrom:
          secretKeyRef:
            name: dbcreds
            key: plainhost

securityContext:
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 11000
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"

# Enabled postgres
postgresql:
  enabled: true
  existingSecret: "dbcreds"
  postgresqlUsername: spotweb
  postgresqlDatabase: spotweb
