image:
  repository: bitnami/nginx
  pullPolicy: IfNotPresent
  tag: latest

appImage:
  repository: jbaten/phpfpm-app
  pullPolicy: IfNotPresent
  tag: 0.1.0@sha256:f9b813042e5e35c36e19b67029f010b7b5f85688081549960b7eabbd351b72d7

# See more environment variables in the babybuddy documentation
# https://hub.docker.com/r/jgeusebroek/spotweb
env:
  # TZ:

service:
  main:
    ports:
      main:
        port: 11000
        targetPort: 80

persistence:
  config:
    enabled: true
    mountPath: "/config"

# Enabled mariadb
mariadb:
  enabled: true
  mariadbUsername: mini
  mariadbDatabase: mini
  existingSecret: "mariadbcreds"

# Php Fpm Service settings
phpfpmService:
  name: phpfpm
  type: NodePort
  phpfpmPort: 9000